#cloud-config
autoinstall:
  version: 1  # Erforderliche Versionsangabe für die Autoinstall-Konfiguration.

  # Pakete, die auf dem System installiert werden sollen.
  packages:
    - ubuntu-desktop
    - vim
    - net-tools
    - lynis
    - citrix-workspace
    - forticlient
    - openvpn

  # Hinzufügen von Snap-Paketen zum System.
  snaps:
    - name: firefox
    - name: gnome-3-38-2004
    - name: gtk-common-themes
    - name: snap-store
    - name: snapd-desktop-integration

  # Benutzeridentität wird festgelegt.
  identity:
    realname: 'Ubuntu User'
    username: ubuntu_test
    password: '73f4a33d231345c656d72cdcbeceaa7543ab9f1e06c87a07d1fc83d21f579c00183fb3cffec3604e328331250695901707e6459a6db42562ba86bb20247b0663'
    hostname: ubuntu-desktop

  # Direktes Layout wird verwendet, manuelle Partitionierung wird spezifiziert.
  storage:
    config:
      - {ptable: gpt, path: /dev/sda, wipe: superblock-recursive, preserve: false, grub_device: true}
        # Eine GUID Partition Table (GPT) wird auf /dev/sda erstellt, alle Daten werden gelöscht.
      - {device: /dev/sda, size: 50G, flag: 'boot', number: 1, type: 'ef00'}
        # Eine 50 GB große EFI System Partition wird erstellt.
      - {device: /dev/sda, size: 50G, flag: '', number: 2, type: '8304'}
        # Eine 50 GB große Root-Partition wird erstellt.
      - {device: /dev/sda, size: -1, flag: '', number: 3, type: '8309'}
        # Der verbleibende Speicherplatz wird für die Home-Partition verwendet.
      - {type: format, volume: /dev/sda1, fstype: fat32}
        # Die EFI Systempartition wird mit FAT32 formatiert.
      - {type: format, volume: /dev/sda2, fstype: ext4}
        # Die Root-Partition wird mit ext4 formatiert.
      - {type: format, volume: /dev/sda3, fstype: ext4}
        # Die Home-Partition wird mit ext4 formatiert.
      - {type: mount, path: /, device: /dev/sda2}
        # Die Root-Partition wird auf / gemountet.
      - {type: mount, path: /home, device: /dev/sda3}
        # Die Home-Partition wird auf /home gemountet.

  # Frühe Befehle zur Kernel-Konfiguration.
  early-commands:
    - echo 'linux-generic-hwe-22.04' > /run/kernel-meta-package

  # Späte Befehle zur Systemkonfiguration und Reinigung.
  late-commands:
    - "curtin in-target -- sed -i /etc/default/grub -e 's/GRUB_CMDLINE_LINUX_DEFAULT=\".*\"/GRUB_CMDLINE_LINUX_DEFAULT=\"quiet splash\"/'"
    - "curtin in-target -- update-grub"
    - "rm /target/etc/netplan/00-installer-config.yaml"
    - "echo 'network:\n  version: 2\n  renderer: NetworkManager' > /target/etc/netplan/01-network-manager-all.yaml"
    - "curtin in-target -- apt-get remove -y ubuntu-server ubuntu-server-minimal"
    - "curtin in-target -- apt-get install -y cloud-init"
    - "curtin in-target -- apt-get autoremove -y"
