#cloud-config
autoinstall:
  version: 1
  locale: de_DE  # Setzt die Systemsprache auf Deutsch (Deutschland)
  keyboard:
    layout: de   # Tastaturlayout auf Deutsch einstellen
    variant: ""  # Keine spezifische Tastaturvariante ausgewählt

storage:
  layout:
    name: lvm  # Verwendung von LVM für die Partitionierung
  config:
    - ptable: gpt
      path: /dev/sda
      wipe: superblock-recursive
      preserve: false
      name: ''
      grub_device: true
      # Erstellt eine GUID Partition Table (GPT) auf /dev/sda, löscht alle bestehenden Daten
    - device: /dev/sda
      size: 1G
      flag: ''
      number: 1
      type: 'ef00'
      # Erstellt eine 1 GB große Partition für das EFI-System (/boot/efi)
    - device: /dev/sda
      size: -1
      type: '8309'
      number: 2
      # Nutzt den verbleibenden Speicherplatz auf /dev/sda für die Hauptpartition
    - type: format
      volume: /dev/sda1
      fstype: fat32
      label: boot
      # Formatiert die EFI-Systempartition mit FAT32
    - type: format
      volume: /dev/sda2
      fstype: 'crypto_LUKS'
      # Formatiert die zweite Partition mit LUKS für die Verschlüsselung
    - type: cryptsetup
      volume: /dev/sda2
      name: cryptroot
      # Initialisiert die LUKS-Verschlüsselung auf /dev/sda2
    - type: lvm_volgroup
      name: ubuntu-vg
      devices: ['/dev/mapper/cryptroot']
      # Erstellt eine Volume-Gruppe 'ubuntu-vg' auf dem verschlüsselten Gerät
    - type: lvm_partition
      name: root
      volgroup: ubuntu-vg
      size: '50G'
      # Erstellt ein logisches Volume für das Wurzelverzeichnis mit 50 GB
    - type: lvm_partition
      name: home
      volgroup: ubuntu-vg
      size: '40G'
      # Erstellt ein logisches Volume für /home mit 40 GB
    - type: format
      volume: /dev/ubuntu-vg/root
      fstype: ext4
      # Formatiert das Root-Volume mit ext4
    - type: format
      volume: /dev/ubuntu-vg/home
      fstype: ext4
      # Formatiert das Home-Volume mit ext4
    - type: mount
      path: /
      device: /dev/ubuntu-vg/root
      # Mountet das Root-Volume auf /
    - type: mount
      path: /home
      device: /dev/ubuntu-vg/home
      # Mountet das Home-Volume auf /home

identity:
  hostname: ubuntu-desktop
  username: ubuntu_test
  password: "test123456"
  # Hier sollte ein verschlüsseltes Passwort stehen

ssh:
  install-server: true
  allow-pw: true
  authorized-keys: []

packages:
  - ubuntu-desktop
  - vim
  - net-tools
  - lynis
  - citrix-workspace
  - forticlient
  - openvpn

network:
  version: 2
  ethernets:
    enp3s0:
      dhcp4: true
      # Konfiguriert die Netzwerkschnittstelle enp3s0, um DHCP für IPv4 zu verwenden

late-commands:
  - echo 'cryptroot UUID=$(blkid -o value -s UUID /dev/sda2) none luks,discard,initramfs' >> /target/etc/crypttab
  - echo '/swapfile none swap sw 0 0' >> /target/etc/fstab
  - curtin in-target --target=/target -- swapoff -a
  - curtin in-target --target=/target -- fallocate -l 40G /swapfile
  - curtin in-target --target=/target -- chmod 600 /swapfile
  - curtin in-target --target=/target -- mkswap /swapfile
  - curtin in-target --target=/target -- swapon /swapfile
  # Die obigen Befehle konfigurieren eine Swap-Datei, aktivieren sie und stellen die korrekte Funktionsweise sicher
